import re
import numpy as np
import os

def float_to_q(f, fractional_bits):
    scale_factor = 2.0 ** fractional_bits
    return int(round(f * scale_factor))

def analyze_and_convert(name, data, fractional_bits, total_bits):
    print(f"--- Analyzing and Converting: {name} ---")
    
    float_arr = np.array(data)
    min_float, max_float = np.min(float_arr), np.max(float_arr)
    print(f"Original Float Range:  [{min_float:.6f}, {max_float:.6f}]")
    q_data = [float_to_q(f, fractional_bits) for f in data]

    min_q_val = -(2**(total_bits - 1))
    max_q_val = 2**(total_bits - 1) - 1
    
    clamped_data = [max(min_q_val, min(d, max_q_val)) for d in q_data]
    
    num_clamped = sum(1 for original, clamped in zip(q_data, clamped_data) if original != clamped)
    if num_clamped > 0:
        print(f"WARNING: {num_clamped} values were clamped to fit into {total_bits}-bit range.")
    
    q_arr = np.array(clamped_data)
    min_q, max_q = np.min(q_arr), np.max(q_arr)
    zeros_original = np.sum(float_arr == 0.0)
    zeros_quantized = np.sum(q_arr == 0)
    
    print(f"Quantized Int Range:   [{min_q}, {max_q}] (Fits within [{min_q_val}, {max_q_val}])")
    print(f"Zeros before quantization: {zeros_original}")
    print(f"Zeros after quantization:  {zeros_quantized}")
    print("-" * (len(name) + 30) + "\n")
    
    return clamped_data

def parse_c_file(file_path):
    try:
        with open(file_path, 'r') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return {}
    pattern = re.compile(r'const\s+float\s+([\w\d_]+)\[\d*\]\s*=\s*\{([^}]+)\};', re.DOTALL)
    
    extracted_data = {}
    matches = pattern.finditer(content)
    
    for match in matches:
        name = match.group(1)
        # Extract numbers, splitting by comma and stripping whitespace/f-suffix
        values_str = match.group(2).replace('f', '').strip()
        float_values = [float(v) for v in values_str.split(',') if v.strip()]
        extracted_data[name] = float_values
        
    return extracted_data

def write_header_file(file_name, q_data_map, fractional_bits, total_bits):
    with open(file_name, 'w') as f:
        f.write(f"// Quantized weights for LeNet\n")
        f.write(f"// Format: Signed Q{total_bits - fractional_bits - 1}.{fractional_bits}\n")
        f.write(f"// Generated by Python quantization script\n")
        f.write("\n#include <stdint.h>\n\n")
        
        for name, data in q_data_map.items():
            f.write(f"const int16_t {name}_q{fractional_bits}[{len(data)}] = {{\n    ")
            for i, val in enumerate(data):
                f.write(f"{val}, ")
                if (i + 1) % 12 == 0 and (i + 1) < len(data):
                    f.write("\n    ")
            f.write("\n};\n\n")
    print(f"Successfully wrote quantized weights to '{file_name}'")


if __name__ == "__main__":
    # Configuration for Q4.12 format
    TOTAL_BITS = 16
    FRACTIONAL_BITS = 12
    
    input_c_file = '../sw/baseline/lenet_weights.c'
    output_header_file = 'lenet_weights_fixed.h'

    if not os.path.exists(input_c_file):
        print(f"Error: Input file '{input_c_file}' not found.")
        print("Please make sure the C file is in the same directory as the script.")
    else:
        float_data_map = parse_c_file(input_c_file)
        
        if float_data_map:
            quantized_data_map = {}
            
            for name, data in float_data_map.items():
                quantized_data_map[name] = analyze_and_convert(
                    name, 
                    data, 
                    FRACTIONAL_BITS, 
                    TOTAL_BITS
                )
            
            write_header_file(
                output_header_file, 
                quantized_data_map, 
                FRACTIONAL_BITS, 
                TOTAL_BITS
            )