import re
import os

def parse_h_file(file_path):
    try:
        with open(file_path, 'r') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return {}

    # Regex to find arrays like 'const int16_t array_name[size] = { ... };'
    pattern = re.compile(r'const\s+int16_t\s+([\w\d_]+)\[\d*\]\s*=\s*\{([^}]+)\};', re.DOTALL)
    
    extracted_data = {}
    matches = pattern.finditer(content)
    
    for match in matches:
        name = match.group(1)
        values_str = match.group(2).strip()
        int_values = [int(v) for v in values_str.split(',') if v.strip()]
        extracted_data[name] = int_values
        
    return extracted_data

def write_coe_file(directory, array_name, data, radix=16, width=16):
    file_path = os.path.join(directory, f"{array_name}.coe")
    
    with open(file_path, 'w') as f:
        f.write(f"; COE file for {array_name}\n")
        f.write(f"; Generated by Python h_to_coe_converter.py\n")
        f.write(f"memory_initialization_radix={radix};\n")
        f.write("memory_initialization_vector=\n")
        
        # Write data vector
        for i, val in enumerate(data):
            if radix == 16:
                hex_val = format(val & (2**width - 1), f'0{width//4}x')
                f.write(hex_val)
            else: # radix == 10
                f.write(str(val))
            

            if i == len(data) - 1:
                f.write(";") 
            else:
                f.write(",\n") 
                
    print(f"Successfully created '{file_path}'")

if __name__ == "__main__":
    input_header_file = 'lenet_weights_fixed.h'
    output_directory = 'coe_files'

    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
        print(f"Created output directory: '{output_directory}'")

    if not os.path.exists(input_header_file):
        print(f"Error: Input file '{input_header_file}' not found.")
        print("Please run the 'weight_quantizer_script' first to generate it.")
    else:
        quantized_data_map = parse_h_file(input_header_file)
        
        if not quantized_data_map:
            print(f"No arrays found in '{input_header_file}'.")
        else:
            print(f"\nFound {len(quantized_data_map)} arrays. Converting to COE format...")
            for name, data in quantized_data_map.items():
                write_coe_file(output_directory, name, data)
            print("\nConversion complete.")